name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: doug-m-alexander/blazordiffusion
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tag-semver: |
            {{version}}
            {{major}}.{{minor}}
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: src/Blazor.App
        file: ./src/Blazor.App/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
