name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        file: Dockerfile
        push: true
        tags: BlazorDiffusion:$(date +%s)
        github-token: ${{ github.token }}
